version: 2.1
executors:
  dotnet:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:2.2
    environment:
      NUPKG: MicroBatchFramework.${CIRCLE_TAG}.nupkg
    shell: |
      if [ "${CIRCLE_TAG}" == "" ]; then
        CIRCLE_TAG = "1.0.0"
      fi
jobs:
  build:
    executor: dotnet
    steps:
      - checkout
      - run: dotnet build -c Release -p:Version=${CIRCLE_TAG}
      - run: dotnet test -c Release --no-build
      - run: dotnet pack -c Release --no-build -p:Version=${CIRCLE_TAG}
      - store_artifacts:
          path: ./src/MicroBatchFramework/bin/Release/$(NUPKG)
          destination: $(NUPKG)
  push:
    executor: dotnet
    steps:
      - run: dotnet push $(NUPKG)
workflows:
  version: 2
  build-and-push:
    jobs:
      - build
      - push:
          requires:
            - build
          filters:
            tags:
              only: /.*/