version: 2.1
executors:
  dotnet:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:2.2
    environment:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
      NUGET_XMLDOC_MODE: skip
jobs:
  build:
    executor: dotnet
    steps:
      - checkout
      - run: |
          if [ "${CIRCLE_TAG}" == "" ]; then
            echo 'export CIRCLE_TAG="1.0.0"' >> $BASH_ENV
          fi
      - run: dotnet build -c Release -p:Version=${CIRCLE_TAG}
      - run: dotnet test -c Release --no-build
      - run: dotnet pack ./src/MicroBatchFramework/MicroBatchFramework.csproj -c Release --no-build -p:Version=${CIRCLE_TAG}
      - store_artifacts:
          path: ./src/MicroBatchFramework/bin/Release
          destination: ~/
      - persist_to_workspace:
          root: ~/
          paths:
            - ./src/MicroBatchFramework/bin/Release
  push:
    executor: dotnet
    steps:
      - attach_workspace:
          at: ~/
      - run: dotnet nuget push ./src/MicroBatchFramework/bin/Release/MicroBatchFramework.${CIRCLE_TAG}.nupkg -s https://www.nuget.org/api/v2/package -k ${NUGET_KEY}
workflows:
  version: 2
  build-and-push:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - push:
          requires:
            - build
          filters:
            tags:
              only: /^\d\.\d\.\d.*/
            branches:
              ignore: /.*/