version: 2.1
executors:
  dotnet:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:3.0
    environment:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
      NUGET_XMLDOC_MODE: skip
jobs:
  build-test:
    executor: dotnet
    steps:
      - checkout
      - run: dotnet build -c Debug
      - run: dotnet test -c Debug --no-build
  build-push:
    executor: dotnet
    steps:
      - checkout
      - run: dotnet build -c Release -p:Version=${CIRCLE_TAG}
      - run: dotnet test -c Release --no-build
      - run: dotnet pack ./src/ConsoleAppFramework/ConsoleAppFramework.csproj -c Release --no-build -p:Version=${CIRCLE_TAG}
      - run: dotnet pack ./src/ConsoleAppFramework.WebHosting/ConsoleAppFramework.WebHosting.csproj -c Release --no-build -p:Version=${CIRCLE_TAG}
      - store_artifacts:
          path: ./src/ConsoleAppFramework/bin/Release
          destination: ./ConsoleAppFramework/
      - store_artifacts:
          path: ./src/ConsoleAppFramework.WebHosting/bin/Release
          destination: ./ConsoleAppFramework.WebHosting/
      - run: dotnet nuget push ./src/ConsoleAppFramework/bin/Release/ConsoleAppFramework.${CIRCLE_TAG}.nupkg -s https://www.nuget.org/api/v2/package -k ${NUGET_KEY}
      - run: dotnet nuget push ./src/ConsoleAppFramework.WebHosting/bin/Release/ConsoleAppFramework.WebHosting.${CIRCLE_TAG}.nupkg -s https://www.nuget.org/api/v2/package -k ${NUGET_KEY}
workflows:
  version: 2
  build-and-push:
    jobs:
      - build-test:
          filters:
            tags:
              only: /.*/
      - build-push:
          filters:
            tags:
              only: /^\d\.\d\.\d.*/
            branches:
              ignore: /.*/
