name: Build-Release

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+*"

jobs:
  build-dotnet:
    runs-on: ubuntu-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      NUGET_XMLDOC_MODE: skip
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x
      # set release tag(*.*.*) to env.GIT_TAG
      - run: echo "GIT_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - run: dotnet build -c Release -p:Version=${{ env.GIT_TAG }}
      - run: dotnet test -c Release --no-build
      - run: dotnet pack ./src/ConsoleAppFramework/ConsoleAppFramework.csproj -c Release --no-build -p:Version=${{ env.GIT_TAG }}
      - run: dotnet pack ./src/ConsoleAppFramework.WebHosting/ConsoleAppFramework.WebHosting.csproj -c Release --no-build -p:Version=${{ env.GIT_TAG }}
      - run: dotnet nuget push ./src/ConsoleAppFramework/bin/Release/ConsoleAppFramework.${{ env.GIT_TAG }}.nupkg -s https://www.nuget.org/api/v2/package -k ${{ secrets.NUGET_KEY }}
      - run: dotnet nuget push ./src/ConsoleAppFramework.WebHosting/bin/Release/ConsoleAppFramework.WebHosting.${{ env.GIT_TAG }}.nupkg -s https://www.nuget.org/api/v2/package -k ${{ secrets.NUGET_KEY }}
